name: Debug SwiftBook Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set versionName from tag
        run: |
          TAG="${{ github.event.inputs.release_tag || github.ref_name }}"
          VERSION_NAME="${TAG#v}"
          echo "Setting versionName=$VERSION_NAME"
          sed -i 's/versionName = ".*"/versionName = "'$VERSION_NAME'"/' app/build.gradle.kts

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permissions for gradle
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

      - name: Build Debug APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace || { echo "Gradle build failed"; exit 1; }
          ls -R app/build/outputs/apk || echo "No APK directory found"

      - name: Rename Debug APK
        run: |
          VERSION_NAME=$(grep 'versionName = ' app/build.gradle.kts | head -1 | cut -d '"' -f2)
          NEW_NAME="SwiftBook ${VERSION_NAME} debug.apk"
          mv app/build/outputs/apk/debug/app-debug.apk "$NEW_NAME"
          echo "APK renamed to $NEW_NAME"

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-artifact
          path: SwiftBook*debug.apk
          compression-level: 5