name: Debug MetaPipe Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permissions for gradle
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

      - name: Build Debug APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace || { echo "Gradle build failed"; exit 1; }
          ls -R app/build/outputs/apk || echo "No APK directory found"

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-artifact
          path: app/build/outputs/apk/debug/app-debug.apk
          compression-level: 5